"""HTCondor executor: one job per trial, completion detected by sentinel files.

Nothing is transferred. Every path a job touches — the payload, the geometry,
the analysis chain, the trial's own directory — lives on AFS and is visible from
the worker node, so the job is `source init_key4ship.sh; python3 payload.py
--workdir ...` and the results are already where the driver expects them.

`condor_q` is a watchdog, not the completion signal. A finished job leaves the
queue within seconds, so a poll that misses that window cannot distinguish
"finished" from "never existed"; the sentinel the payload writes is unambiguous
and survives on disk. What `condor_q` is good for is the cases the payload
cannot report on itself: a held job, or a job that vanished (evicted, node
crash) without writing anything. Those are infrastructure failures, and the loop
retries them with the same seed — if the second attempt fails the same way, the
cause is the geometry and not the cluster.

Setting `run_local: true` runs the very same wrapper script as a local
subprocess, which is how the Condor path gets tested without a scheduler (the
existing `generic_condor_multiplePG.sh` uses RUN_LOCAL=1 for the same purpose).
"""

from __future__ import annotations

import logging
import re
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ..core.types import Trial
from ..paths import init_script as default_init_script
from .base import Executor, ExitInfo, Handle, clear_sentinels, read_sentinel

log = logging.getLogger(__name__)

CLUSTER_RE = re.compile(r"submitted to cluster (\d+)")
TERSE_RE = re.compile(r"^(\d+\.\d+)")

# condor's JobStatus codes.
IDLE, RUNNING, REMOVED, COMPLETED, HELD, TRANSFERRING, SUSPENDED = 1, 2, 3, 4, 5, 6, 7

WRAPPER_TEMPLATE = """#!/bin/bash
# Generated by mobo (exec/htcondor.py) — one trial, one job.
#
# Runnable on its own for debugging:   bash {workdir}/job.sh
echo "mobo trial {name} starting on $(hostname) at $(date)"

# key4hep's setup.sh reads unset variables, so -u has to stay off across it.
if [ -z "${{KEY4HEP_STACK:-}}" ]; then
    source {init_script}
fi

cd {workdir} || exit 1

rc=0
{command} || rc=$?

# The payload writes DONE/FAILED itself. If neither is here the payload never
# got far enough to speak, and saying so is far more useful to the loop than
# leaving it to time out.
if [ ! -f DONE ] && [ ! -f FAILED ]; then
    echo "wrapper: the payload left no sentinel (exit code $rc)" > FAILED
fi

echo "mobo trial {name} finished at $(date) with code $rc"
exit $rc
"""

SUBMIT_TEMPLATE = """# Generated by mobo (exec/htcondor.py) — trial {name}
universe                = {universe}
executable              = {workdir}/job.sh
log                     = {workdir}/condor.log
output                  = {workdir}/condor.out
error                   = {workdir}/condor.err
should_transfer_files   = {transfer}
when_to_transfer_output = ON_EXIT
+JobFlavour             = "{flavour}"
request_cpus            = {request_cpus}
request_memory          = {request_memory}
request_disk            = {request_disk}
{extra}queue 1
"""


@dataclass
class CondorConfig:
    flavour: str = "workday"
    universe: str = "vanilla"
    request_cpus: int = 1
    request_memory: str = "2GB"
    request_disk: str = "4GB"
    should_transfer_files: str = "YES"
    # The job writes its results straight into an AFS directory, which needs the
    # submitter's credential to be forwarded. Without this, every trial fails
    # with a permission error the moment it tries to write.
    send_credential: bool = True
    timeout_hours: float = 12.0
    # How long a job may be absent from condor_q with no sentinel before it is
    # declared lost. Generous on purpose: AFS can take a while to show a file
    # written by another machine.
    grace_seconds: float = 600.0
    watchdog_interval: float = 120.0
    poll_interval: float = 60.0
    submit_retries: int = 3
    init_script: str | None = None
    run_local: bool = False
    extra_submit: dict[str, str] = field(default_factory=dict)

    @classmethod
    def from_config(cls, cfg: Any) -> CondorConfig:
        fields = set(cls.__dataclass_fields__)
        kwargs = {k: v for k, v in dict(cfg).items() if k in fields}
        if kwargs.get("extra_submit"):
            kwargs["extra_submit"] = {
                str(k): str(v) for k, v in dict(kwargs["extra_submit"]).items()
            }
        return cls(**kwargs)


@dataclass
class _Job:
    handle: Handle
    proc: Any = None  # only for run_local
    missing_since: float | None = None


class CondorExecutor(Executor):
    def __init__(self, cfg: CondorConfig | None = None) -> None:
        self.cfg = cfg or CondorConfig()
        self._jobs: dict[int, _Job] = {}
        self._last_watchdog = 0.0

    # ── generating the job ───────────────────────────────────────────────────

    def init_script(self) -> Path:
        if self.cfg.init_script:
            return Path(self.cfg.init_script)
        return default_init_script()

    def wrapper_text(self, name: str, cmd: list[str], workdir: Path) -> str:
        return WRAPPER_TEMPLATE.format(
            name=name,
            workdir=str(workdir),
            init_script=str(self.init_script()),
            command=" ".join(_quote(str(c)) for c in cmd),
        )

    def submit_text(self, name: str, workdir: Path) -> str:
        extra = dict(self.cfg.extra_submit)
        if self.cfg.send_credential:
            extra.setdefault("MY.SendCredential", "true")
        extra_lines = "".join(
            f"{key:<23} = {value}\n" for key, value in sorted(extra.items())
        )
        return SUBMIT_TEMPLATE.format(
            name=name,
            workdir=str(workdir),
            universe=self.cfg.universe,
            transfer=self.cfg.should_transfer_files,
            flavour=self.cfg.flavour,
            request_cpus=self.cfg.request_cpus,
            request_memory=self.cfg.request_memory,
            request_disk=self.cfg.request_disk,
            extra=extra_lines,
        )

    def write_job_files(
        self, trial: Trial, cmd: list[str], workdir: Path
    ) -> tuple[Path, Path]:
        workdir = Path(workdir)
        workdir.mkdir(parents=True, exist_ok=True)
        wrapper = workdir / "job.sh"
        wrapper.write_text(self.wrapper_text(trial.name, cmd, workdir))
        wrapper.chmod(0o755)
        submit = workdir / "job.sub"
        submit.write_text(self.submit_text(trial.name, workdir))
        return wrapper, submit

    # ── contract ─────────────────────────────────────────────────────────────

    def submit(self, trial: Trial, cmd: list[str], workdir: Path) -> Handle:
        workdir = Path(workdir)
        wrapper, submit_file = self.write_job_files(trial, cmd, workdir)
        clear_sentinels(workdir)

        handle = Handle(trial_id=trial.trial_id, workdir=workdir, attempt=trial.attempt)
        if self.cfg.run_local:
            # Closed when the job is reaped; the subprocess owns it until then.
            stream = open(workdir / "condor.out", "w")  # noqa: SIM115
            proc = subprocess.Popen(
                ["bash", str(wrapper)],
                cwd=str(workdir),
                stdout=stream,
                stderr=subprocess.STDOUT,
                start_new_session=True,
            )
            handle.job_id = f"local:{proc.pid}"
            self._jobs[trial.trial_id] = _Job(handle, proc=proc)
            log.info(
                "submitted %s locally through the condor wrapper (pid %d)",
                handle.name,
                proc.pid,
            )
            return handle

        handle.job_id = self._condor_submit(submit_file, workdir)
        self._jobs[trial.trial_id] = _Job(handle)
        log.info("submitted %s to condor as %s", handle.name, handle.job_id)
        return handle

    def _condor_submit(self, submit_file: Path, workdir: Path) -> str:
        """condor_submit with retries: the schedd is occasionally busy."""
        last = ""
        for attempt in range(1, self.cfg.submit_retries + 1):
            proc = subprocess.run(
                ["condor_submit", str(submit_file)],
                cwd=str(workdir),
                capture_output=True,
                text=True,
            )
            if proc.returncode == 0:
                job_id = parse_cluster_id(proc.stdout)
                if job_id:
                    return job_id
                last = f"could not parse a cluster id from: {proc.stdout.strip()}"
            else:
                last = (proc.stderr or proc.stdout).strip()
            log.warning(
                "condor_submit attempt %d/%d failed: %s",
                attempt,
                self.cfg.submit_retries,
                last,
            )
            if attempt < self.cfg.submit_retries:
                time.sleep(5.0 * attempt)
        raise RuntimeError(f"condor_submit failed: {last}")

    def poll(self) -> list[tuple[Handle, ExitInfo]]:
        finished: list[tuple[Handle, ExitInfo]] = []
        for trial_id, job in list(self._jobs.items()):
            info = self._status(job)
            if info is None:
                continue
            self._jobs.pop(trial_id, None)
            if job.proc is not None and job.proc.stdout is not None:
                job.proc.stdout.close()
            finished.append((job.handle, info))
        return finished

    def _status(self, job: _Job) -> ExitInfo | None:
        sentinel = read_sentinel(job.handle.workdir)
        if sentinel is not None:
            return sentinel

        age = time.time() - job.handle.submitted_at
        if self.cfg.timeout_hours and age > self.cfg.timeout_hours * 3600.0:
            self.cancel(job.handle)
            return ExitInfo(False, "timeout", f"no sentinel after {age / 3600.0:.1f} h")

        if job.proc is not None:  # run_local
            if job.proc.poll() is None:
                return None
            # The wrapper always writes a sentinel before exiting, so getting
            # here means it was killed outright.
            return ExitInfo(
                False,
                "lost",
                f"the wrapper exited with {job.proc.returncode} and no sentinel",
            )

        return self._watch(job)

    def _watch(self, job: _Job) -> ExitInfo | None:
        """condor_q as a watchdog: held jobs, and jobs that quietly vanished."""
        statuses = self._queue_snapshot()
        if statuses is None:  # the scheduler did not answer; try again later
            return None

        status = statuses.get(str(job.handle.job_id))
        if status == HELD:
            log.warning("%s is held; removing it so it can be retried", job.handle.name)
            self.cancel(job.handle)
            return ExitInfo(False, "held", "the job went on hold")
        if status is not None:
            job.missing_since = None
            return None

        # Not in the queue and no sentinel yet. That is normal for a few
        # seconds (AFS latency), and a lost job after that.
        now = time.time()
        if job.missing_since is None:
            job.missing_since = now
            return None
        if now - job.missing_since < self.cfg.grace_seconds:
            return None
        return ExitInfo(
            False,
            "lost",
            "gone from condor_q for %.0f s without writing a sentinel"
            % (now - job.missing_since),
        )

    def _queue_snapshot(self) -> dict[str, int] | None:
        """{job id: JobStatus} for our jobs, or None if condor_q was no help.

        Rate-limited: the loop polls often, and one condor_q per trial per poll
        would be rude to a shared scheduler.
        """
        now = time.time()
        cached = getattr(self, "_queue_cache", None)
        if cached is not None and now - self._last_watchdog < self.cfg.watchdog_interval:
            return cached

        ids = [j.handle.job_id for j in self._jobs.values() if j.handle.job_id]
        if not ids:
            return {}
        try:
            proc = subprocess.run(
                ["condor_q", *[str(i) for i in ids], "-af:j", "JobStatus"],
                capture_output=True,
                text=True,
                timeout=120,
            )
        except (OSError, subprocess.SubprocessError) as exc:
            log.warning("condor_q failed (%s); no watchdog this round", exc)
            return None
        if proc.returncode != 0:
            log.warning(
                "condor_q returned %d: %s", proc.returncode, proc.stderr.strip()[:200]
            )
            return None

        snapshot = parse_queue(proc.stdout)
        self._queue_cache = snapshot
        self._last_watchdog = now
        return snapshot

    def cancel(self, handle: Handle) -> None:
        job = self._jobs.pop(handle.trial_id, None)
        if job is not None and job.proc is not None:
            job.proc.terminate()
            return
        if not handle.job_id:
            return
        try:
            subprocess.run(
                ["condor_rm", str(handle.job_id)],
                capture_output=True,
                text=True,
                timeout=60,
            )
        except (OSError, subprocess.SubprocessError) as exc:
            log.warning("condor_rm %s failed: %s", handle.job_id, exc)

    def adopt(self, trial: Trial) -> Handle | None:
        """Re-attach to a job that outlived the driver.

        Two ways this can work: the job is still in the queue, or it already
        finished and left its sentinel. Both are better than re-running a
        simulation that has already been paid for.
        """
        if not trial.workdir:
            return None
        workdir = Path(trial.workdir)
        handle = Handle(
            trial_id=trial.trial_id,
            workdir=workdir,
            job_id=trial.job_id,
            attempt=trial.attempt,
            submitted_at=trial.submitted_at or time.time(),
        )
        if read_sentinel(workdir) is not None:
            self._jobs[trial.trial_id] = _Job(handle)
            return handle
        if self.cfg.run_local or not trial.job_id:
            return None

        snapshot = self._queue_snapshot_uncached([str(trial.job_id)])
        if snapshot and str(trial.job_id) in snapshot:
            self._jobs[trial.trial_id] = _Job(handle)
            return handle
        return None

    def _queue_snapshot_uncached(self, ids: list[str]) -> dict[str, int] | None:
        try:
            proc = subprocess.run(
                ["condor_q", *ids, "-af:j", "JobStatus"],
                capture_output=True,
                text=True,
                timeout=120,
            )
        except (OSError, subprocess.SubprocessError):
            return None
        return parse_queue(proc.stdout) if proc.returncode == 0 else None

    def shutdown(self, cancel_running: bool = False) -> None:
        if not cancel_running:
            return
        for handle in list(self.in_flight):
            self.cancel(handle)

    @property
    def in_flight(self) -> list[Handle]:
        return [job.handle for job in self._jobs.values()]

    @property
    def capacity(self) -> int | None:
        return None  # the batch system decides; the loop's max_in_flight rules


# ── parsing condor's output ──────────────────────────────────────────────────


def parse_cluster_id(stdout: str) -> str | None:
    """`12345.0` out of whatever condor_submit printed."""
    terse = TERSE_RE.match(stdout.strip())
    if terse:
        return terse.group(1)
    match = CLUSTER_RE.search(stdout)
    return f"{match.group(1)}.0" if match else None


def parse_queue(stdout: str) -> dict[str, int]:
    """`condor_q -af:j JobStatus` output -> {job id: status}."""
    snapshot: dict[str, int] = {}
    for line in stdout.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[1].isdigit():
            snapshot[parts[0]] = int(parts[1])
    return snapshot


def _quote(value: str) -> str:
    """Shell-quote only when needed, so the wrapper stays readable."""
    if value and all(c.isalnum() or c in "-_./=:," for c in value):
        return value
    return "'" + value.replace("'", "'\\''") + "'"
