#!/bin/bash
# Generated by mobo (exec/htcondor.py) — one trial, one job.
#
# Runnable on its own for debugging:   bash /WORKDIR/job.sh
echo "mobo trial t00042 starting on $(hostname) at $(date)"

# key4hep's setup.sh reads unset variables, so -u has to stay off across it.
if [ -z "${KEY4HEP_STACK:-}" ]; then
    source /repo/init_key4ship.sh
fi

cd /WORKDIR || exit 1

rc=0
python3 /pkg/payload.py --workdir /WORKDIR || rc=$?

# The payload writes DONE/FAILED itself. If neither is here the payload never
# got far enough to speak, and saying so is far more useful to the loop than
# leaving it to time out.
if [ ! -f DONE ] && [ ! -f FAILED ]; then
    echo "wrapper: the payload left no sentinel (exit code $rc)" > FAILED
fi

echo "mobo trial t00042 finished at $(date) with code $rc"
exit $rc
